export enum EventTypes {
  PatientSummary = 'Patient Summary',
  Camp = 'Camp',
  VisitType = 'Visit Type',
  Vitals = 'Vitals',
  Evaluation = 'Evaluation',
  Complaint = 'Complaint',
  Treatment = 'Treatment',
  Diagnosis = 'Diagnosis',
  MedicinesInStock = 'Medicines in Stock',
  MedicinesOTC = 'Medicines OTC',
  ControlledMedicines = 'Controlled Medicines',
  Prescriptions = 'Prescriptions',
  Allergies = 'Allergies',
  MedicalHistory = 'Medical History',
  Notes = 'Notes',
  Covid19Screening = 'COVID-19 Screening',
  MedicalPathologies = 'Medical Pathologies',
  PatientDetails = 'Patient Details'
}