export const LocalizedStrings = {
  "en": {
    patients: "Patients",
    PATIENTS: "< PATIENTS",
    welcome: "Welcome Back",
    date: "Date",
    dob: "Date of Birth",
    DOB: "DOB",
    sex: "Sex",
    gender: "Gender",
    GENDER: "GENDER",
    patientSummary: "Patient Summary",
    noContent: "No content yet",
    age: "AGE",
    edit: "EDIT",
    back: "< BACK",
    save: "SAVE",
    confirm: "CONFIRM",
    cancel: "CANCEL",
    yes: "Y",
    no: "N",
    //next two not in arabic
    positive: "Positive",
    negative: "Negative",
    true: "True",
    false: "False",
    newVisit: "New Visit",
    //next two not in arabic
    deleteVisit: "Delete Visit",
    confirmDeleteVisit: "Are you sure you want to delete this visit?",
    newPatient: "New Patient",
    newEntry: "New Entry",
    patientSnapshot: "Patient Snapshot",
    closeSnapshot: "Close Snapshot",
    firstName: "First Name",
    firstName1: "First Name 1",
    firstName2: "First Name 2",
    surname: "Surname",
    surname1: "Surname 1",
    surname2: "Surname 2",
    country: "Country",
    hometown: "Hometown",
    selectDob: "Select DOB",
    phone: "Phone",
    patientSearch: "Search patient name...",
    search: "Search",
    minAge: "Min Age",
    maxAge: "Max Age",
    advancedFilters: "Advanced Filters ▼",
    hideFilters: "Hide Filters",
    clearFilters: "Clear All Filters",
    camp: "Camp",
    vitals: "Vitals",
    examination: "Examination",
    notes: "Notes",
    complaint: "Complaint",
    treatment: "Treatment",
    diagnosis: "Diagnosis",
    medicineDispensed: "Medicine Dispensed",
    prescriptions: "Prescriptions",
    allergies: "Allergies",
    medicalHistory: "Medical History",
    covidScreening: "COVID-19 Screening",
    enterTextHere: "Enter text here.",
    visitDate: "Visit Date",
    visitHistory: "Visit History",
    visitEvents: "Visit Events",
    visitType: "Visit Type",
    trends: "TRENDS",
    eventType: "Event Type",
    datePrescribed: "Date Prescibed",
    provider: "Provider",
    severity: "Severity",
    onsetDate: "Onset Date",
    departure: "Departure",
    to: "to",
    return: "Return",
    fever: "Fever?",
    dryCough: "Dry Cough?",
    diffBreathing: "Difficulty Breathing?",
    soreThroat: "Sore Throat?",
    chestPain: "Chest Pain?",
    confusion: "New Confusion?",
    bluish: "Bluish Lips or Face?",
    fatigue: "Fatigue?",
    aches: "Aches and Pains?",
    headache: "Headache?",
    diabetes: "Diabetes",
    cardioDisease: "Cardiovascular Disease?",
    pulmonaryDisease: "Pulmonary Disease?",
    renalDisease: "Renal Disease?",
    malignancy: "Malignancy?",
    pregnant: "Pregnant or 2 weeks postpartum?",
    immunocompromised: "Immunocompromised?",
    exposureKnown: "Recent contact with individuals with known COVID-19?",
    exposureSuspected: "Recent contact with individuals with suspected COVID-19?",
    travelIran: "Recent travel to Iran?",
    travel: "Recent travel to High Risk Countries?",
    testIsolate: "Test/Isolate Patient",
    noAction: "No Action Necessary",
    syncFailure: "Database Sync Failure!",
    syncFailureConnection: "Check internet connection",
    syncFailureSystem: "Contact system administrator",
    syncSuccess: "Database Sync Success",

    //NV events
    patientDetails: "Patient Details",
    medicalNum: "Medical #",
    dentalNum: "Dental #",
    optometryNum: "Optometry #",
    patientId: "Patient ID #",
    community: "Community",
    zone: "Zone",
    block: "Block",
    lot: "Lot",
    emergencyPhone: "Emergency Contact Cellphone",
    mother: "Mother’s full name",
    motherPhone: "Mother’s cellphone",
    father: "Father’s full name",
    fatherPhone: "Father’s cellphone",
    partner: "Partner’s full name",
    partnerPhone: "Partner’s cellphone",
    employer: "Employer",
    insurance: "Medical Insurance & Policy",

    malnutrition: "Malnutrition Antecedents",
    prenatal: "Prenatal Antecedents",
    sexualHx: "Sexual History",
    nutrition: "Nutrition",
    parasiteTreatment: "Most recent Date of Parasite Treatment",
    treatmentDate: "Treatment Date",
    familyHx: "Family Medical History",
    surgeryHx: "Previous Surgeries",
    vaccinations: "Vaccinations",

    glycemia: "Glycemia (mg)",
    weight: "Weight (kg)",
    weightLb: "Weight (lb)",
    idealWeight: "Ideal Weight (kg)",
    bloodPressure: "Blood Pressure",
    pulse: "Pulse",
    respiration: "Respiration",
    sats: "Oxygen Saturation (%)",
    height: "Height (m)",
    temp: "Temp (C°)",
    bloodType: "Blood Type",

    clinicalEvaluation: "Clinical Evaluation",
    doctor: "Doctor",
    reason: "Reason for Medical Exam",
    observations: "General Observations",
    medications: "Current Medications",
    breastExam: "Breast Exam",
    communityVisit: "Visit in Community",
    promoterVisit: "Visit to Health Promoter with First Aid Kits",
    refusal: "Refusal of Services",
    nextVisitDate: "Date of Next Visit",
    nextVisitReason: "Reason for Next Visit",
    nextVisit: "Next Visit",

    //4,5,6
    medicinesInStock: "Medicines from Stock",
    medicinesOTC: "Medicines OTC",
    controlledMedicines: "Controlled Medicines",
    medicine: "Medicine",
    format: "Presentation (i.e. tablet / bottle size / concentration)",
    dosage: "Dosage",
    days: "Days",

    //7
    medicalPathologies: "Medical Pathologies",
    miscarriages: "Number of Miscarriages",
    foodAllergies: "Allergies to Food",
    animalAllergies: "Allergies to Animals",
    atmosphereAllergies: "Allergies to Atmosphere",
    insectAllergies: "Allergies to Insects",
    latexAllergies: "Allergies to Latex",
    medicineAllergies: "Allergies to Medicine",
    otherAllergies: "Allergies - Other",
    tonsillitis: "Tonsillitis / sore throat",
    anemic: "Anemic",
    arthritisRA: "Reumatoid Arthritis",
    asthma: "Asthma",
    neckPain: "Neck pain",
    cervicovaginitis: "Cervicovaginitis including Vaginal Fungi",
    cSection: "Cesarean Sections",
    sciaticPain: "Sciatic pain",
    cholesterol: "Cholesterol",
    infantColic: "Infant Colic",
    conjunctivitis: "Conjunctivitis",
    covid: "COVID-19",
    malnourishment: "Malnourishment",
    //diabetes
    migraines: "Body & head pain including migraines",
    diarrhea: "Acute Diarrhea",
    ecocardiogram: "Ecocardiogram",
    electrocardiogram: "Ecocardiogram",
    pregnancies: "Pregnancies",
    chikungunya: "Mosquito transmitted: chikungunya",
    dengue: "Mosquito transmitted: dengue",
    malaria: "Mosquito transmitted: malaria",
    otherMosquito: "Mosquito transmitted:other",
    zika: "Mosquito transmitted: zika",
    copd: "COPD",
    gastritis: "GERD/Gastritis/H. Pylori",
    scabies: "Scabies",
    lastPAP: "Last PAP",
    vaginalFluid: "Vaginal fluid",
    hypertension: "Hypertension or Cardiac condition",
    hypothyroidism: "Hypothyroidism",
    bacterialResp: "Respiratory infection - Bacterial",
    viralResp: "Respiratory infection - Viral (including Flu)",
    uti: "UTI",
    renalFailure: "Chronic Renal Failure",
    breastfeeding: "Breastfeeding",
    lumbago: "Lumbago",
    menopause: "Menopause / Climateric",
    nausea: "Nausea",
    nephrolithiasisRenal: "Nephrolithiasis or renal colic",
    diabeticNeuropathy: "Diabetic Neuropathy",
    obesity: "Obesity",
    osteoarthritis: "Osteoarthritis",
    otitis: "Otitis Externa or Media",
    paralysis: "Paralysis",
    parasites: "Parasites",
    skinHealthy: "Skin - no infection",
    skinUlcers: "Skin - ulcers",
    skinInfected: "Skin - infected including cuts",
    lice: "Lice",
    postnatalVisit: "Post-natal Visit",
    prenatalVisit: "Prenatal Visit",
    eyeProb: "Eye problems",
    emotionalProb: "Emotional problems",
    gynecologicalProb: "General Gynecological problems",
    parkinsons: "Neurological Problems - Parkinson's",
    epilepsy: "Neurological Problems - Epilepsy",
    neurologicalProb: "Neurological Problems - Other",
    therapistReferred: "Referred to Therapist",
    developmentallyDelayed: "Developmentally delayed",
    vitamins: "Risk or Needing Vitamins",
    lastMenstruation: "Last Menstruation",
    hiv: "HIV",
    vomiting: "Vomiting",
    other: "Other",
    details: "Details",

    psychologicalPathologies: "Psychological Pathologies",
    anxiety: "Anxiety",
    nuclearFamily: "Attention to the Nuclear Family",
    selfEsteem: "Self Esteem",
    attentionDeficit: "Attention Deficit within family or school",
    depression: "Depression",
    grief: "Grief",
    stress: "Acute Seasonal Stress",
    disfunctionalFamily: "Disfunctional family",
    hyperactivity: "Hyperactivity",
    inappropriatePlay: "Inappropriate Play",
    languageProblems: "Language Development Problems",
    behavioralProblems: "Behavior Problems - Learned Behaviors",
    schoolProblems: "Problems in School",
    psychosis: "Psychosis",
    suicidal: "Suicidal",
    personalityDisorders: "Personality Disorders",
    trauma: "Trauma",
    psychologicalEvaluations: "Psychological Evaluations in General",
    domesticViolenceFamily: "Domestic Violence - family",
    domesticViolenceSpouse: "Domestic Violence - spouse",
    referralHospital: "Referral to hospital",

    //9
    householdEnvironment: "Household Environment",
    potableWater: "Potable Water",
    animals: "Animals",
    gasCooking: "Gas Cooking",
    woodCooking: "Wood Cooking",
    householdSize: "How many People Live in the House",
    toilet: "Toilet",
    latrine: "Latrine",
    familyViolence: "Family Violence",

    //10
    labOrders: "Lab Orders",
    hematicBiometry: "Complete Hematic Biometry & Platelets",
    urinalysis: "Urinalysis",
    biochemistry: "Clinical Biochemistry Test I",
    lipidProfile: "Lipid Profile",
    pregnancyTest: "Pregnancy Test",
    immunologyTest: "Immunology Test",
    PAPTest: "PAP Test",
    serologyTest: "Serology Test",
    stoolTest: "Stool exam & Fecal cytology",
    fecalAntigens: "Fecal Antigens - Helicobacter Pylori",
    HIVTest: "HIV - with Consent Form",

    //11
    labTests: "Lab Tests",
    CBCImmature: "CBC - immature neutrophils",
    CBCMCHC: "CBC - MCHC",
    CBCMCH: "CBC - MCH",
    CBCBasophils: "CBC - Basophils",
    CBCEosinophils: "CBC - Eosinophils",
    CBCHematocrit: "CBC - Hematocrit",
    CBCHemoglobin: "CBC - Hemoglobin",
    CBCLymphocytes: "CBC - Lymphocytes",
    CBCMonocytes: "CBC - Monocytes",
    CBCPlatelets: "CBC - Platelets",
    CBCSegmented: "CBC - segmented neutrophils",
    CBCWBC: "CBC - WBC",
    CBCPlateletCount: "CBC - platelet count",
    CBCRBC: "CBC - RBC",
    CBCMCV: "CBC - MCV",
    biochemUric: "Clinical Biochemistry I - Uric Acid",
    biochemCreatinine: "Clinical Biochemistry I - Creatinine",
    biochemGlucose: "Clinical Biochemistry I - Glucose",
    lipidCholesterol: "Lipid profile - Total Cholesterol (Su",
    lipidHDL: "Lipid Profile - HDL Cholesterol",
    lipidLDL: "Lipid Profile - LDL",
    lipidTriglycerides: "Lipid Profile - Triglycerides",
    lipidVLDL: "Lipid Profile - VLDL Cholesterol",
    fecalMononuclear: "Fecal Exam & Differential Fecal Cytology - Mononuclear",
    fecalPolymophonuclear: "Fecal Exam & Differential Fecal Cytology - Polymorphonuclear",
    fecalBacteria: "Fecal Exam & Microscopic Fecal Cytology - Bacteria",
    fecalErythrocytes: "Fecal exam & Microscopic Fecal Cytology - Erythrocytes",
    fecalLeukocytes: "Fecal Exam & Microscopic Fecal Cytology - Leukocytes",
    fecalOthers: "Fecal Exam & Microscopic Fecal Cytology - Others",
    fecalCysts: "Fecal Exam & Microscopic Fecal Cytology - Cysts",
    fecalTrophozoites: "Fecal Exam & Microscopic Fecal Cytology - Trophozoites",
    fecalPH: "Fecal Exam & Fecal Chemical Cytology - pH",
    fecalReducers: "Fecal Exam & Fecal Chemical Cytology - Az Reducers",
    fecalOccult: "Fecal Exam & Fecal Chemical Cytology - Occult Blood",
    fecalColor: "Fecal Exam & Macroscopic Fecal Cytology - Color",
    fecalObservations: "Fecal Exam & Macroscopic Fecal Cytology - Observations",
    fecalConsistency: "Fecal Exam & Maccroscopic Fecal Cytology - Consistency",
    pregnancyHemogravindex: "Pregnancy - Hemogravindex",
    pregnancyGravindex: "Pregnancy - Gravindex",
    microbiologyPilori: "Microbiology - H. Pilori in Blood",
    microbiologyMalaria: "Microbiology - Malaria",
    serologyStrep: "Serology - Rapid Strep A",
    serologyRheumatoid: "Serology - Rheumatoid Factor",
    serologyOthers: "Serology - Others",
    serologyProtein: "Serology - C Reactive Protein",
    serologyVDRL: "Serology - VDRL or RPR",
    serologyVIH: "Serology - VIH",
    serologyVSG: "Serology - VSG",
    RHFactor: "Rh Factor",

    //12
    labUrineTests: "Lab Urine Tests",
    colorPhysical: "Physical Color",
    aspectsPhysical: "Physical Aspects",
    sedimentPhysical: "Physical Sediment",
    densityPhysical: "Physical Density",
    proteinsChem: "Chemical - Proteins",
    hemoglobinChem: "Chemical - Hemoglobin",
    ketonicChem: "Chemical - Ketonic Body",
    pHChem: "Chemical - pH",
    urobilinogenChem: "Chemical - Urobilinogen",
    glucoseChem: "Chemical - Glucose",
    bilirubinsChem: "Chemical - Bilirubins",
    leukocytesChem: "Chemical - Leukocytes",
    nitriteChem: "Chemical - Nitrite",
    epithelialMicro: "Microscopic - Epithelial Cells/field",
    leukocytesMicro: "Microscopic - Leukocytes/field",
    erythrocytesMicro: "Microscopic - Erythrocytes/field",
    cylindersMicro: "Microscopic - Cylinders/field",
    crystalsMicro: "Microscopic - Crystals",
    bacteriaMicro: "Microscopic - Bacteria/field",
    yeastsMicro: "Microscopic - Yeasts",
    cRenalMicro: "Microscopic - C Renal",
    hMucousMicro: "Microscopic - H Mucous",
    observationsMicro: "Microscopic - Observations",

    //13
    PAPResults: "PAP Results",
    adequateCyto: "Cytological - Adequate smear",
    incompleteCyto: "Cytological - Adequate but limited smear - incomplete data",
    cellularityCyto: "Cytological - Adequate but limited smear - Poor cellularity",
    fixationCyto: "Cytological - Adequate but limited smear - Poor fixation",
    hemorrhageCyto: "Cytological - Adequate but limited smear - Hemorrhage",
    exudateCyto: "Cytological - Adequate but limited smear - Presence of inflammatory exudate",
    endocervicalCyto: "Cytological - Adequate but limited smear - Absence of endocervical cells",
    inadequateCyto: "Cytological - Inadequate smear",
    bleedingCyto: "Cytological - Inadequate smear - Intense bleeding",
    fixationInadequateCyto: "Cytological - Inadequate smear - Bad fixation",
    squamous: "Atypical squamous cells",
    USSquamous: "Squamous Atypia - ASC-US",
    HSquamous: "Squamous Atypia - ASC-H",
    lgsil: "LGSIL",
    cellularLgsil: "Low Grade Squamous Intraepithelial Lesion - Human Papillomavirus Cellular Changes",
    dysplasiaLgsil: "Low Grade Squamous Intraepithelial Lesion - Mild Dysplasia / CIN I",
    hgsil: "HGSIL",
    cinHgsil: "HGSIL / CIN II",
    dysplasiaHgsil: "HGSIL - Severe Dysplasia / CIN III",
    carcinomaHgsil: "HGSIL - Carcinoma in Situ",
    negIntraepithelial: "Negative of intraepithelial lesion and malignant cells",
    aisCarcinoma: "Carcinoma - Adenocarcinoma in Situ (AIS)",
    invasiveCarcinoma: "Carcinoma - Invasive Adenocarcinoma",
    agcCarcinoma: "Carcinoma - Glandular Atypia AGC",
    endocervicalCarcinoma: "Carcinoma - Endocervical",
    endometrialCarcinoma: "Carcinoma - Endometrial",
    neoplasiaCarcinoma: "Carcinoma - Neoplasia not ruled out",
    nosCarcinoma: "Carcinoma - NOS",
    iscc: "ISCC",
    atrophy: "Others - Atrophy",
    coccoid: "Others - Coccoid Bacteria",
    regenerative: "Others - Regenerative Changes",
    candida: "Others - Candida sp",
    bv: "Others - BV",
    herpes: "Others - Herpes Virus",
    inflammation: "Others - Inflammation",
    trichomonas: "Others - Vaginal Trichomonas",

    //14
    ultrasound: "Ultrasound",
    abdominal: "Abdominal",
    joints: "Joints",
    neck: "Neck",
    doppler: "Doppler veins",
    breast: "Breast",
    firstOB: "OB complete / obstetric - 1st trimester",
    secondOB: "OB complete / obstetric -2nd trimester",
    thirdOB: "OB complete / obstetric - 3rd trimester",
    softTissues: "Soft Tissues",
    pelvic: "Pelvic",
    prostate: "Prostate",
    renal: "Renal",
    testicular: "Testicular",
    goiter: "Goiter",
    wrappedCord: "Wrapped Cord",
    cholelithiasis: "Cholelithiasis",
    prostate1: "Prostate growth - Grade I",
    prostate2: "Prostate growth - Grade II",
    prostate3: "Prostate growth - Grade III",
    prostate4: "Prostate growth - Grade IV",
    endometrialThickening: "Endometrial thickening",
    splenomegaly: "Splenomegaly",
    mildHepatic: "Hepatic Steatosis - Mild",
    moderateHepatic: "Hepatic Steatosis - Moderate",
    severeHepatic: "Hepatic Steatosis - Severe",
    hepatomegaly: "Hepatomegaly",
    cirrhosis: "Cirrhosis",
    venousInsufficiency: "Venous insufficiency",
    mildRenal: "Renal CKD - Mild",
    moderateRenal: "Renal CKD - Moderate",
    severeRenal: "Renal CKD - Severe",
    nephrolithiasis: "Nephrolithiasis",
    complexMasses: "Complex Masses",
    benignNodules: "Benign Nodules",
    malignantNodules: "Malignant Nodules",
    thyroidNodules: "Thyroid Nodules",
    normalUltrasound: "Normal Ultrasound",
    polycysticOvaries: "Polycystic Ovaries",
    simpleOvarianCysts: "Simple Ovarian Cysts",

    //15
    familyPlanning: "Family Planning",
    ageSexualRelations: "Age began sexual relations",
    numberChildren: "Number of children",
    moreChildren: "Do you want more children",
    abnormalBleeding: "Abnormal menstrual bleeding",
    varicose: "Varicose veins",
    tubalSterilization: "Sterilization - Tubal / minilap",
    vasectomySterilization: "Sterilization - Vasectomy",
    stdType: "STD (type)",
    injection: "Injection",
    iudBC: "Birth Control IUD",
    implantBC: "Birth Control Implant",
    pillsBC: "Birth Control Pills",
    condoms: "Use of Condoms",
    sexOrientation: "Sexual Orientation",
    married: "Married",
    permanentPartner: "Permanent Partner",

    //16
    dentalOrigin: "Dental Origin (ON or JHC)",
    bernabe: "Bernabé",
    canon: "Cañon",
    clubLaEsperanza: "Club la Esperanza P Sheyla",
    elShaddai: "El Shaddai",
    hogar: "Hogar de Fé",
    jinotepe: "Jinotepe",
    laHermosa: "La Hermosa",
    leonDeJuda: "Leon de Judá",
    losNinn: "Los Ninn",
    luzVida: "Luz y Vida P Dolores",
    manantialDeVida: "Manantial de Vida",
    maranatha: "Maranatha",
    matagalpa: "Matagalpa",
    monteDeSion: "Monte de Sión",
    nuevaJerusalen: "Nueva Jerusalén",
    obreroLevitico: "Obrero Levítico",
    posoltegaJoseLara: "Posoltega P Jose Lara",
    riosDeAguaViva: "Rios de Agua Viva",
    rivas: "Rivas",
    verboSur: "Verbo Sur",
    jubileeHouseCommunity: "Jubilee House Community",
    otherFeedingCenter: "Other (name of feeding center)",

    //17
    dentalTreatment: "Dental Treatment",
    toothbrush: "Toothbrush",
    consult: "Consult",
    extraction: "Extraction",
    fluoride: "Flouride",
    floss: "Floss",
    cleaningFirst: "Cleaning - 1st visit",
    cleaningFirstYear: "Cleaning - 1st visit current year",
    cleaningSecond: "Cleaning - 2nd visit current year",
    toothpaste: "Toothpaste",
    xray: "X-ray",
    amalgamaRestoration: "Restoration - Amalgama",
    metalRestoration: "Restoration - Metal (temporary) crown",
    ionomeroRestoration: "Restoration - Ionomero",
    mriRestoration: "Restoration - MRI (temporary)",
    spaceRestoration: "Restoration - Space maintainer",
    resinRestoration: "Restoration - Resin",
    zoeRestoration: "Restoration - Zoe (temporary)",
    acetateRestoration: "Restoration - Acetate (temporary) crown",
    pulpotomyRestoration: "Restoration - Pulpotomy",
    sdFluoride: "SD Fluoride",
    sealant: "Sealant",
    teaching: "Teaching cleaning techniques",
    impression: "Impression",

    //18
    programTrainings: "Program Trainings",
    asthmaSubject: "Subject - Asthma",
    pregnancySubject: "Subject - Pregnancy",
    dispensarizados1Subject: "Subject - Group I Dispensarizados",
    dispensarizados2Subject: "Subject - Group II Dispensarizados",
    dispensarizados3Subject: "Subject - Group III Dispensarizados",
    dispensarizados4Subject: "Subject - Group IV Dispensarizados",
    breastfeedingSubject: "Subject - Breast feeding",
    girlsGroupSubject: "Subject - Girls' Group",
    lbgtqSubject: "Subject - LBGTQ",
    boysOlderSubject: "Subject - Boys' Group - older",
    boysYoungerSubject: "Subject - Boys' Group - younger",
    newMothersSubject: "Subject - New Mothers",
    familyPlanningSubject: "Subject - Family Planning",
    toddlerMothersSubject: "Subject - Toddler Mothers",
    healthPromotersSubject: "Subject - Health Promoters",
    hivSubject: "Subject - HIV",
    otherSubject: "Subject - Other",

    //19
    xrayOrders: "X-Ray Orders",
    hipAntero: "Hip Rx - Antero",
    hipLateral: "Hip Rx - Lateral",
    hipPosterior: "Hip Rx - Posterior",
    retrogradeCystogram: "Retrograde Cystogram Rx",
    cranialAntero: "Cranial Rx - Antero",
    cranialLateral: "Cranial Rx - Lateral",
    cranialPosterior: "Cranial Rx - Posterior",
    femurAntero: "Femur Rx - Antero",
    femurLateral: "Femur Rx - Lateral",
    femurPosterior: "Femur Rx - Posterior",
    footAntero: "Foot Rx - Antero",
    standingLateral: "Standing Rx - Lateral",
    standingOblique: "Standing Rx - Oblique",
    footPosterior: "Foot Rx - Posterior",
    ivPyelogram: "Intravenous Pyelogram Rx",
    kneeAntero: "Knee Rx - Antero",
    kneeLateral: "Knee Rx - Lateral",
    kneePosterior: "Knee Rx - Posterior",
    tibiaAntero: "Tibia Rx - Antero",
    tibiaLateral: "Tibia Rx - Lateral",
    tibiaPosterior: "Tibia Rx - Posterior",
    ankleAntero: "Ankle Rx - Antero",
    ankleLateral: "Ankle Rx - Lateral",
    anklePosterior: "Ankle Rx - Posterior",
    chestAntero: "Chest Rx - Antero",
    chestLateral: "Chest Rx - Lateral",
    chestPosterior: "Chest Rx - Posterior",

    //20
    xrayResults: "X-Ray Results",
    arthritis: "Arthritis",
    cardiomegaly: "Cardiomegaly",
    ureteralDuplication: "Complete and Partial Ureteral Duplication",
    lungDisease: "Lung disease",
    fibrosis: "Fibrosis",
    fractures: "Fractures",
    pneumonia: "Pneumonia / COPD / TB",
    pulmonaryNodule: "Pulmonary nodule",
    osteoporosis: "Osteoporosis",
    ectopicKidney: "Ectopic Kidney",
    rinonHerradura: "Rinon in Herradura",
    tumor: "Tumor",

    //21
    optometry: "Optometry",
    cataract: "Cataract",
    cataractOperation: "Cataract operation",
    glasses: "Wear Glasses - type (reading / distance/ etc)",
    glassesDuration: "How long glasses have been worn - years",
    orangeReflection: "Orange Reflection",
    visualAcuityOD: "Visual Acuity without lenses AV OD",
    visualAcuityOS: "Visual Acuity without lenses AV OS",
    autorefractorOD: "Autorefractor OD",
    autorefractorOS: "Autorefractor OS",
    phoropterOD: "Phoropter OD",
    phoropterOS: "Phoropter OS",
    phoropterADD: "Phoropter ADD",
    lensesOD: "Lenses Delivered OD",
    lensesOS: "Lenses Delivered OS",
    lensesADD: "Lenses Delivered ADD",
    visualAcuityLensesOD: "Visual Acuity with Lenses AV OD",
    visualAcuityLensesOS: "Visual Acuity with Lenses AV OS",

    //22
    accidentReport: "Accident Report",
    accidentWork: "Accident at work",
    description: "Description and where / how",

    traumaDetails: "Trauma details",
    referralSpecialist: "Referral to Specialist",
    followUpVisit: "Follow-Up Visit",

  },
  "sp": {
    patients: "Pacientes",
    PATIENTS: "< PACIENTES",
    welcome: "Bienvenido de vuelta",
    date: "Fecha",
    dob: "Fecha de nacimiento ",
    DOB: "Fecha de nacimiento ",
    sex: "Sexo",
    gender: "Género",
    GENDER: "GENERO",
    patientSummary: "Resumen del paciente",
    noContent: "No hay contenido aún",
    age: "EDAD",
    edit: "EDITAR",
    back: "< Volver Atrás",
    save: "GUARDAR",
    confirm: "CONFIRMAR",
    cancel: "CANCELAR",
    yes: "Sí",
    no: "No",
    positive: "Positivo",
    negative: "Negativo",
    true: "Verdader@",
    false: "Fals@",
    deleteVisit: "Eliminar visita",
    confirmDeleteVisit: "¿Estás seguro de que deseas eliminar esta visita?",
    newVisit: "Visita Nueva",
    newPatient: "Paciente Nuevo",
    newEntry: "Ingreso Nuevo",
    patientSnapshot: "Perfil del Paciente",
    closeSnapshot: "Cerrar Perfil",
    firstName: "Nombre",
    firstName1: "Nombre 1",
    firstName2: "Nombre 2",
    surname: "Apellido",
    surname1: "Apellido 1",
    surname2: "Apellido 2",
    country: "País",
    hometown: "Ciudad de origen",
    selectDob: "Seleccione fecha de nacimiento",
    phone: "Teléfono",
    patientSearch: "Buscar nombre del paciente...",
    search: "Buscar",
    minAge: "Edad Mínima",
    maxAge: "Edad Máxima",
    advancedFilters: "Filtros ▼",
    hideFilters: "Ocultar Filtros",
    clearFilters: "Borrar Filtros",
    camp: "Nombre del campo de refugiados",
    vitals: "Signos Vitales",
    examination: "Examen físico",
    notes: "Notas",
    complaint: "Queja/Preocupación médica",
    treatment: "Tratamiento",
    diagnosis: "Diagnóstico",
    medicineDispensed: "Medicamento suscrito",
    prescriptions: "Recetas de medicamentos",
    allergies: "Alergias",
    medicalHistory: "Historial Médico",
    covidScreening: "Prueba de COVID-19",
    enterTextHere: "Introduzca texto aquí",
    visitDate: "Fecha de la visita",
    visitHistory: "Historia de la visita",
    visitEvents: "Eventos durante la visita",
    visitType: "Tipo de visita",
    trends: "Tendencias",
    eventType: "Tipo de evento",
    datePrescribed: "Fecha de prescripción",
    provider: "Proveedor médico",
    severity: "Severidad",
    onsetDate: "Fecha de comienzo de los síntomas",
    departure: "Ida",
    to: "a ",
    return: "Vuelta",
    fever: "¿Fiebre?",
    dryCough: "¿Tos seca?",
    diffBreathing: "¿Dificultad al respirar?",
    soreThroat: "¿Dolor de garganta?",
    chestPain: "¿Dolor de pecho?",
    confusion: "¿Nueva confusión?",
    bluish: "¿Labios azulados/ violetas?",
    fatigue: "¿Fatiga?",
    aches: "¿Dolores y molestias?",
    headache: "¿Dolor de cabeza?",
    diabetes: "Diabetes",
    cardioDisease: "¿Problemas del corazón?",
    pulmonaryDisease: "¿Enfermedad en los pulmones?",
    renalDisease: "¿Enfermedad de los riñones?",
    malignancy: "¿Cáncer?",
    pregnant: "¿Mujer recién dada a luz?",
    immunocompromised: "¿Inmunocomprometido? / ¿Tiene las defensas bajas?",
    exposureKnown: "¿Ha tenido contacto reciente con personas diagnosticadas con COVID-19?",
    exposureSuspected: "¿Ha tenido contacto reciente con personas que pueden tener COVID-19?",
    travelIran: "¿Ha viajado recientemente a Irán?",
    travel: "¿Ha viajado recientemente a países de alto riesgo de contagio?",
    testIsolate: "Hacerle la prueba/Aislar al paciente",
    noAction: "No es necesario tomar ninguna acción",
    syncFailure: "¡Fallo de sincronización!",
    syncFailureConnection: "Verifica la conexión a internet",
    syncFailureSystem: "Comuníquese con el administrador del sistema",
    syncSuccess: "Éxito en la sincronización",
    //NV events
    patientDetails: "Detalles del Paciente",
    medicalNum: "Exp. Medico #",
    dentalNum: "Exp. Dental #",
    optometryNum: "Exp. Optometry #",
    patientId: "Cedula #",
    community: "Comunidad",
    zone: "Zona",
    block: "Manzana",
    lot: "Lote",
    emergencyPhone: "Cel. por Emergencia",
    mother: "Madre",
    motherPhone: "Cel. Madre",
    father: "Padre",
    fatherPhone: "Cel. Padre",
    partner: "Compañer@",
    partnerPhone: "Cel. Compañer@",
    employer: "Empleador",
    insurance: "Seguro Medico y ID#",

    malnutrition: "Antecedentes de Desnutrición",
    prenatal: "Antecedentes Prenatales",
    sexualHx: "Antecedentes Historia Sexual",
    nutrition: "Alimentación",
    parasiteTreatment: "Fecha más reciente del Tratamiento del Parásito",
    treatmentDate: "Fecha de tratamiento",
    familyHx: "Antecedentes Patologicos de Familiares",
    surgeryHx: "Cirugías Previas",
    vaccinations: "Vacunas",

    glycemia: "Glicemia (mg)",
    weight: "Peso (kg)",
    weightLb: "Peso (libra)",
    idealWeight: "Peso Ideal (kg)",
    bloodPressure: "Presión Arterial",
    pulse: "Pulso",
    respiration: "Respiración",
    sats: "Saturación de Oxígeno (%)",
    height: "Talla (m)",
    temp: "Temp (C°)",
    bloodType: "Tipo de Sangre",

    clinicalEvaluation: "Evaluación Clinica",
    doctor: "Médic@",
    reason: "Razón del Examen Médico",
    observations: "Observaciones Generales",
    medications: "Medicamentos Actuales",
    breastExam: "Examen de mamas",
    communityVisit: "Visita a la Comunidad",
    promoterVisit: "Visita a Promotores con Botiquines",
    refusal: "Constancia de Responsabilidad",
    nextVisitDate: "Fecha de Cita de Seguimiento",
    nextVisitReason: "Motiva de la Cita de Seguimiento",
    nextVisit: "Siguiente visita",

    //4,5,6
    medicinesInStock: "Medicamentos de Bodega",
    medicinesOTC: "Medicamentos Prescritos",
    controlledMedicines: "Medicamentos Controlados",
    medicine: "Medicamentos",
    format: "Presentación (e.j tableta, tamaño de botella, concentración)",
    dosage: "Dosis",
    days: "Dias",

    //7
    medicalPathologies: "Patologias Medicas",
    miscarriages: "Abortos",
    foodAllergies: "Alérgias a Alimentos",
    animalAllergies: "Alérgias a Animales",
    atmosphereAllergies: "Alérgias a la Atmósfera",
    insectAllergies: "Alérgias a Insectos",
    latexAllergies: "Alérgias al Látex",
    medicineAllergies: "Alérgias a Medicamentos",
    otherAllergies: "Alérgias a Otra",
    tonsillitis: "Amigdalitis / dolor de la garganta",
    anemic: "Anemia",
    arthritisRA: "Artritis Reumatoide",
    asthma: "Asma",
    neckPain: "Cervicalgia",
    cervicovaginitis: "Cervicovaginitis incl. Hongos de la Vagina",
    cSection: "Cesareas",
    sciaticPain: "Ciatalgia",
    cholesterol: "Colesterol",
    infantColic: "Cólico Infantil",
    conjunctivitis: "Conjuntivitis",
    covid: "COVID-19",
    malnourishment: "Desnutricion",
    migraines: "Dolor cuerpo y/o cabeza inc. migraña",
    diarrhea: "EDA (diarrea)",
    ecocardiogram: "Ecocardiograma",
    electrocardiogram: "Electrocardiograma",
    pregnancies: "Embarazos",
    chikungunya: "Enfermedades transmitidas por mosquitos: chikungunya",
    dengue: "Enfermedades transmitidas por mosquitos: dengue",
    malaria: "Enfermedades transmitidas por mosquitos: malaria",
    otherMosquito: "Enfermedades transmitidas por mosquitos: otro",
    zika: "Enfermedades transmitidas por mosquitos: zika",
    copd: "EPOC",
    gastritis: "ERGE/gastritis/H.Pylori",
    scabies: "Escabiosis",
    lastPAP: "Fecha del Último PAP",
    vaginalFluid: "Flujo Vaginal",
    hypertension: "Hipertension o condicion Cardiaca",
    hypothyroidism: "Hipotiroidismo",
    bacterialResp: "Infeccion respiratoria - bacteriana",
    viralResp: "Infeccion respiratoria - viral (incl. Gripe)",
    uti: "Infeccion Urinaria (ITU)",
    renalFailure: "IRC insuficiente renal cronica",
    breastfeeding: "Lactancia Materna",
    lumbago: "Lumbago",
    menopause: "Menopausico / Climaterio",
    nausea: "Nausea",
    nephrolithiasisRenal: "Nefrolitiasis o cólico nefrítico",
    diabeticNeuropathy: "Neuropatia Diabetica",
    obesity: "Obesidad",
    osteoarthritis: "Osteoartritis",
    otitis: "Otitis Externa o Media ",
    paralysis: "Paralisis",
    parasites: "Parasitosis",
    skinHealthy: "Piel - condicion no infectada",
    skinUlcers: "Piel - úlceras",
    skinInfected: "Piel - condicion infectada incluye heridas",
    lice: "Piojos",
    postnatalVisit: "Post-natal Visita",
    prenatalVisit: "Prenatal Visita",
    eyeProb: "Problemas del Ojo",
    emotionalProb: "Problemas Emocionales",
    gynecologicalProb: "Problemas Ginecologicos generales",
    parkinsons: "Problemas Neurológicos Enfermedad de Parkinson",
    epilepsy: "Problemas Neurológicos Epilepsia",
    neurologicalProb: "Problemas Neurologicos Otros",
    therapistReferred: "Referencia a Terapeuta",
    developmentallyDelayed: "Retraso en el Desarrollo",
    vitamins: "Riesgo de o necesita Vitaminas",
    lastMenstruation: "Ultima Menstruacion",
    hiv: "VIH",
    vomiting: "Vómito",
    other: "Otra",
    details: "Detalles",

    //8
    psychologicalPathologies: "Patologias Psicología",
    anxiety: "Ansiedad",
    nuclearFamily: "Atencion al Nucleo Familiar",
    selfEsteem: "Autoestima",
    attentionDeficit: "Defasis de Atención inicial en familia o escuela",
    depression: "Depresión",
    grief: "Duelo",
    stress: "Estrés Estacional Agudo",
    disfunctionalFamily: "Familias Disfuncionales",
    hyperactivity: "Hiperactividad",
    inappropriatePlay: "Juegos no Adecuados",
    languageProblems: "Problemas Desarrollo inicial en el Lenguaje",
    behavioralProblems: "Problemas de Comportamiento de Conductas Aprendidas",
    schoolProblems: "Problemas en la Escuela",
    psychosis: "Psicosis",
    suicidal: "Suicida",
    personalityDisorders: "Trastornos de Personalidad",
    trauma: "Trauma",
    psychologicalEvaluations: "Valoraciones Psicológicas en General",
    domesticViolenceFamily: "Violencia Doméstica - familia",
    domesticViolenceSpouse: "Violencia Doméstica - matrimonio",
    referralHospital: "Transferencia al hospital",

    //9
    householdEnvironment: "Ambiente del Hogar",
    potableWater: "Agua Potableersonas Viven en la Casa",
    animals: "Animales",
    gasCooking: "Cocina con Gas",
    woodCooking: "Cocina de Leña ",
    householdSize: "Cuantas Personas Viven en la Casa",
    toilet: "Inodoro",
    latrine: "Letrina ",
    familyViolence: "Violencia Intrafamiliar",

    //10
    labOrders: "Ordenes de Laboratorio",
    hematicBiometry: "Biometria Hematica Completa & Plaquetas",
    urinalysis: "Examen General de Orina (EGO)",
    biochemistry: "Prueba Bioquimica Clinica I",
    lipidProfile: "Prueba Bioquimica Clinica II",
    pregnancyTest: "Prueba de Embarazo",
    immunologyTest: "Prueba de Immunologia",
    PAPTest: "Prueba de PAP",
    serologyTest: "Prueba de Serologia",
    stoolTest: "Prueba EGH & Citología Fecal",
    fecalAntigens: "Prueba Helicobacter Pylori en Heces",
    HIVTest: "VIH - con consentimiento",

    //11
    labTests: "Exámenes de Laboratorio",
    CBCImmature: "BHC & C.INMADURAS",
    CBCMCHC: "BHC & CHCM",
    CBCMCH: "BHC & HCM",
    CBCBasophils: "BHC & Plaquetas - Basofilos",
    CBCEosinophils: "BHC & Plaquetas - Eosinofilos",
    CBCHematocrit: "BHC & Plaquetas - Hematocrito",
    CBCHemoglobin: "BHC & Plaquetas - Hemoglobina",
    CBCLymphocytes: "BHC & Plaquetas - Linfocitos",
    CBCMonocytes: "BHC & Plaquetas - Monocitos",
    CBCPlatelets: "BHC & Plaquetas - Plaquetas",
    CBCSegmented: "BHC & Plaquetas - Segmentados",
    CBCWBC: "BHC & SERIE BLANCA",
    CBCPlateletCount: "BHC & SERIE PLAQUETARIA",
    CBCRBC: "BHC & SERIE ROJA",
    CBCMCV: "BHC & VCM",
    biochemUric: "Bioquimica Clinica I - Acido Urico",
    biochemCreatinine: "Bioquimica Clinica I - Creatinina",
    biochemGlucose: "Bioquimica Clinica I - Glucosa",
    lipidCholesterol: "Bioquimica Clinica II - Colesterol Total",
    lipidHDL: "Bioquimica Clinica II - HDL Colesterol",
    lipidLDL: "Bioquimica Clinica II - LDL Colesterol",
    lipidTriglycerides: "Bioquimica Clinica II - Trigliceridos",
    lipidVLDL: "Bioquimica Clinica II - VLDL Colesterol",
    fecalMononuclear: "Citologia Fecal & Diferencial - Mononucleares",
    fecalPolymophonuclear: "Citologia Fecal & Diferencial - Polimorfonucleares",
    fecalBacteria: "Citologia Fecal & Microscopico - Bacterias",
    fecalErythrocytes: "Citologia Fecal & Microscopico - Eritrocitos",
    fecalLeukocytes: "Citologia Fecal & Microscopico - Leucocitos",
    fecalOthers: "Citologia Fecal & Microscopico - Otros",
    fecalCysts: "Citologia Fecal & Microscopico - Quistes",
    fecalTrophozoites: "Citologia Fecal & Microscopico - Trofozoitos",
    fecalPH: "Citologia Fecal & Quimico -  pH",
    fecalReducers: "Citologia Fecal & Quimico - Az Reductores",
    fecalOccult: "Citologia Fecal & Quimico - Sangre oculta",
    fecalColor: "EGH & Macroscopico - Color",
    fecalObservations: "EGH & Macroscopico - Observaciones",
    fecalConsistency: "EGH & Macroscopico- Consistencia",
    pregnancyHemogravindex: "Embarazo - Hemogravindex",
    pregnancyGravindex: "Embarazo - Gravindex",
    microbiologyPilori: "Microbiologia - H.Pilory en sangre",
    microbiologyMalaria: "Microbiologia - Malaria",
    serologyStrep: "Serologia - ASLO",
    serologyRheumatoid: "Serologia - Factor Reumatoide",
    serologyOthers: "Serologia - Otros",
    serologyProtein: "Serologia - Proteina C Reactiva",
    serologyVDRL: "Serologia - VDRL o RPR",
    serologyVIH: "Serologia - VIH",
    serologyVSG: "Serologia - VSG",
    RHFactor: "Factor Rh",

    //12
    labUrineTests: "Examen de Orina (EGO)",
    colorPhysical: "Fisico - Color",
    aspectsPhysical: "Fisico - Aspecto",
    sedimentPhysical: "Fisico - Sedimento",
    densityPhysical: "Fisico - Densidad",
    proteinsChem: "Quimico - Proteinas",
    hemoglobinChem: "Quimico - Hemoglobina",
    ketonicChem: "Quimico - Cuerpo Cetonicos",
    pHChem: "Quimico - pH",
    urobilinogenChem: "Quimico - Urobilinogeno",
    glucoseChem: "Quimico - Glucosa",
    leukocytesChem: "Quimico - Bilirubinas",
    bilirubinsChem: "Quimico - Leucocitos",
    nitriteChem: "Quimico - Nitritos",
    epithelialMicro: "Microscopico - Celulas Epiteliales... xcampo",
    leukocytesMicro: "Microscopico - Leucocitos... xcampo",
    erythrocytesMicro: "Microscopico - Eritrocitos... xcampo",
    cylindersMicro: "Microscopico - Cilindros... xcampo",
    crystalsMicro: "Microscopico - Cristales",
    bacteriaMicro: "Microscopico - Bacterias...xcampo",
    yeastsMicro: "Microscopico - Hongos",
    cRenalMicro: "Microscopico - C Renales",
    hMucousMicro: "Microscopico - H Mucosos",
    observationsMicro: "Microscopico - Observaciones",

    //13
    PAPResults: "Examenes de PAP",
    adequateCyto: "Citológico - Frotis adecuado",
    incompleteCyto: "Citológico - Frotis adecuado pero limitado - datos incompletos",
    cellularityCyto: "Citológico - Frotis adecuado pero limitado - Celularidad escasa",
    fixationCyto: "Citológico - Frotis adecuado pero limitado - Fijacion deficiente",
    hemorrhageCyto: "Citológico - Frotis adecuado pero limitado - Hemorragia",
    exudateCyto: "Citológico - Frotis adecuado pero limitado - Presencia de exudado inflamatorio",
    endocervicalCyto: "Citológico - Frotis adecuado pero limitado - Ausencia de celulas endocervicales",
    inadequateCyto: "Citológico - Frotis inadecuado",
    bleedingCyto: "Citológico - Frotis inadecuado - Hemorragia intensa",
    fixationInadequateCyto: "Citológico - Frotis inadecuado - Mala fijación",
    squamous: "Atipia Escamosa",
    USSquamous: "Atipia Escamosa - ASC-US",
    HSquamous: "Atipia Escamosa - ASC-H",
    lgsil: "Lesión Escamosa Intraepitelial de Bajo Grado",
    cellularLgsil: "Lesión Escamosa Intraepitelial de Bajo Grado - Cambios Ceelulares del Virus del Papiloma Humano",
    dysplasiaLgsil: "Lesión Escamosa Intraepitelial de Bajo Grado - Displasia Leve / NIC I",
    hgsil: "Lesión Escamosa Intraepitelial de alto Grado",
    cinHgsil: "Lesión Escamosa Intraepitelial de alto Grado - Displasia Moderada / NIC II",
    dysplasiaHgsil: "Lesión Escamosa Intraepitelial de alto Grado - Displasia Severa / NIC III",
    carcinomaHgsil: "Lesión Escamosa Intraepitelial de alto Grado - Carcinoma in Situ",
    negIntraepithelial: "Negativa de Lesión intraepitelial y de células malignas",
    aisCarcinoma: "Carcinoma - Adenocarcinoma in Situ (AIS)",
    invasiveCarcinoma: "Carcinoma - Adenocarcinoma Invasor",
    agcCarcinoma: "Carcinoma - Atipia Glandular AGC",
    endocervicalCarcinoma: "Carcinoma - Endocervical",
    endometrialCarcinoma: "Carcinoma - Endometrial",
    neoplasiaCarcinoma: "Carcinoma - No se Descarta Neoplasia",
    nosCarcinoma: "Carcinoma - NOS",
    iscc: "Carcinoma de Células Escamosas invasor",
    atrophy: "Otros - Atrofia",
    coccoid: "Otros - Bacterias Cocoides",
    regenerative: "Otros - Cambios Regenerativos",
    candida: "Otros - Candida sp",
    bv: "Otros - Gardnerella Vaginal",
    herpes: "Otros - Herpes Virus",
    inflammation: "Otros - Inflamación",
    trichomonas: "Otros - Tricomonas Vaginales",

    //14
    ultrasound: "Ultrasonidos y Resultados",
    abdominal: "Abdominal",
    joints: "Articulaciones",
    neck: "Cuello",
    doppler: "Doppler venoso",
    breast: "Mamas",
    firstOB: "OB completo / obstetrico - 1 trimestre",
    secondOB: "OB completo / obstetrico - 2 trimestre",
    thirdOB: "OB completo / obstetrico - 3 trimestre",
    softTissues: "Tejidos Blandos",
    pelvic: "Pélvico",
    prostate: "Prostático",
    renal: "Renal",
    testicular: "Testicular",
    goiter: "Bocio",
    wrappedCord: "Circular de Cordón",
    cholelithiasis: "Colelitiasis",
    prostate1: "Crecimiento prostático - Grado I",
    prostate2: "Crecimiento prostático - Grado II",
    prostate3: "Crecimiento prostático - Grado III",
    prostate4: "Crecimiento prostático - Grado IV",
    endometrialThickening: "Engrosamiento  endometría",
    splenomegaly: "Esplenomegalia",
    mildHepatic: "Esteatosis Hepática - Leve",
    moderateHepatic: "Esteatosis Hepática - Moderada",
    severeHepatic: "Esteatosis Hepática - Severe",
    hepatomegaly: "Hepatomegalia",
    cirrhosis: "Hepetopatía Crónica (Cirrosis)",
    venousInsufficiency: "Insuficiencia venosa",
    mildRenal: "IRC Renal - Leve",
    moderateRenal: "IRC Renal - Moderada",
    severeRenal: "IRC Renal - Severe",
    nephrolithiasis: "Litiasis Renal",
    complexMasses: "Masas Complejas",
    benignNodules: "Nodulos Benignos",
    malignantNodules: "Nodulos Malignos",
    thyroidNodules: "Nodulos Tiroideos",
    normalUltrasound: "Normal Ultrasonido",
    polycysticOvaries: "Ovarios Poliquísticos",
    simpleOvarianCysts: "Quistes Simples de Ovario",

    //15
    familyPlanning: "Planificación",
    ageSexualRelations: "Edad en que comienza la vida sexual",
    numberChildren: "Cuantos hijos/hijas tiene",
    moreChildren: "Desea tener mas hijos/hijas",
    abnormalBleeding: "Sangrado Anormal",
    varicose: "Venas Varicosas",
    tubalSterilization: "Esterilizacion - Minilap",
    vasectomySterilization: "Esterilizacion - Vasectomia",
    stdType: "ETS (que tipo)",
    injection: "Planificación - Depo",
    iudBC: "Planificacion - DIU",
    implantBC: "Planificacion - Implante",
    pillsBC: "Planificacion - Tableta",
    condoms: "Usa de Condones",
    sexOrientation: "Orientación Sexual",
    married: "Casad@",
    permanentPartner: "Compañer@",

    //16
    dentalOrigin: "Origen Dental (ON o JHC)",
    bernabe: "Bernabé",
    canon: "Cañon",
    clubLaEsperanza: "Club la Esperanza P Sheyla",
    elShaddai: "El Shaddai",
    hogar: "Hogar de Fé",
    jinotepe: "Jinotepe",
    laHermosa: "La Hermosa",
    leonDeJuda: "Leon de Judá",
    losNinn: "Los Ninn",
    luzVida: "Luz y Vida P Dolores",
    manantialDeVida: "Manantial de Vida",
    maranatha: "Maranatha",
    matagalpa: "Matagalpa",
    monteDeSion: "Monte de Sión",
    nuevaJerusalen: "Nueva Jerusalén",
    obreroLevitico: "Obrero Levítico",
    posoltegaJoseLara: "Posoltega P Jose Lara",
    riosDeAguaViva: "Rios de Agua Viva",
    rivas: "Rivas",
    verboSur: "Verbo Sur",
    jubileeHouseCommunity: "Jubilee House Community",
    otherFeedingCenter: "Other (name of feeding center)",

    //17
    dentalTreatment: "Tratamientos Dental",
    toothbrush: "Cepillos",
    consult: "Consulta",
    extraction: "Extracción",
    fluoride: "Fluor",
    floss: "Hilo dental",
    cleaningFirst: "Limpieza - 1ra Vez",
    cleaningFirstYear: "Limpieza - 1ra Vez en el año",
    cleaningSecond: "Limpieza -2ndo en el año",
    toothpaste: "Pasta dental",
    xray: "Radiografía",
    amalgamaRestoration: "Restauración - Amalgama",
    metalRestoration: "Restauración - Corona (temporal) de metal",
    ionomeroRestoration: "Restauración - Ionomero",
    mriRestoration: "Restauración - IRM (temporal)",
    spaceRestoration: "Restauración - Mantenedor de espacio",
    resinRestoration: "Restauración - Resina",
    zoeRestoration: "Restauración - Zoe (temporal)",
    acetateRestoration: "Restauración -Corona (temporal) de acetato",
    pulpotomyRestoration: "Restauración - Pulpotomía",
    sdFluoride: "SD Flúor",
    sealant: "Selladores",
    teaching: "Tecnica de limpieza",
    impression: "Toma de impresión",

    //18
    programTrainings: "Charlas en los Programas",
    asthmaSubject: "Tema  - Asma",
    pregnancySubject: "Tema - Embarazada",
    dispensarizados1Subject: "Tema  - Grupo I Dispensarizados",
    dispensarizados2Subject: "Tema - Grupo II Dispensarizados",
    dispensarizados3Subject: "Tema - Grupo III Dispensarizados",
    dispensarizados4Subject: "Tema - Grupo IV Dispensarizados",
    breastfeedingSubject: "Tema - Lactancia Materna",
    girlsGroupSubject: "Tema - Las Lobas",
    lbgtqSubject: "Tema - LBGTQ",
    boysOlderSubject: "Tema - Los Leones - jóvenes",
    boysYoungerSubject: "Tema - Los Leones - niños pequeños",
    newMothersSubject: "Tema - Madres Nuevas",
    familyPlanningSubject: "Tema - Planificación",
    toddlerMothersSubject: "Tema - Post Programa para Madres",
    healthPromotersSubject: "Tema - Promotores",
    hivSubject: "Tema - VIH",
    otherSubject: "Tema - Otros",

    //19
    xrayOrders: "Ordenes de Rx",
    hipAntero: "Rx de Cadera - Antero",
    hipLateral: "Rx de Cadera - Lateral",
    hipPosterior: "Rx de Cadera - Posterior",
    retrogradeCystogram: "Rx de Cistograma Retrógrado",
    cranialAntero: "Rx de Cráneo - Antero",
    cranialLateral: "Rx de Cráneo - Lateral",
    cranialPosterior: "Rx de Cráneo - Posterior",
    femurAntero: "Rx de Femur - Antero",
    femurLateral: "Rx de Femur - Lateral",
    femurPosterior: "Rx de Femur - Posterior",
    footAntero: "Rx de Pie - Antero",
    standingLateral: "Rx de Pie - Lateral",
    standingOblique: "Rx de Pie - Oblicua",
    footPosterior: "Rx de Pie - Posterior",
    ivPyelogram: "Rx de Pielograma Intravenoso",
    kneeAntero: "Rx de Rodilla - Antero",
    kneeLateral: "Rx de Rodilla - Lateral",
    kneePosterior: "Rx de Rodilla - Posterior",
    tibiaAntero: "Rx de Tibia - Antero",
    tibiaLateral: "Rx de Tibia - Lateral",
    tibiaPosterior: "Rx de Tibia - Posterior",
    ankleAntero: "Rx de Tobillo - Antero",
    ankleLateral: "Rx de Tobillo - Lateral",
    anklePosterior: "Rx de Tobillo - Posterior",
    chestAntero: "Rx de Tórax - Antero",
    chestLateral: "Rx de Tórax - Lateral",
    chestPosterior: "Rx de Tórax - Posterior",

    //20
    xrayResults: "Diagnosticos de Rx",
    arthritis: "Artritis",
    cardiomegaly: "Cardiomegalia",
    ureteralDuplication: "Duplicación Ureteral Completa y Parcial",
    lungDisease: "Enfermedad Pulmonar",
    fibrosis: "Fibrosis",
    fractures: "Fracturas",
    pneumonia: "Neumonía / EPOC / TB",
    pulmonaryNodule: "Nódulo Pulmonar",

    osteoporosis: "Osteoporosis",
    ectopicKidney: "Riñón Ectópico",
    rinonHerradura: "Riñón en Herradura",
    tumor: "Tumor",

    //21
    optometry: "Optometria",
    cataract: "Cataratas",
    cataractOperation: "Operado de Cataratas",
    glasses: "Usa lentes - tipo",
    glassesDuration: "Lentes por cuanto tiempo - años",
    orangeReflection: "Reflejo Naranjo",
    visualAcuityOD: "Agudeza Visual sin lentes AV  OD",
    visualAcuityOS: "Agudeza Visual sin lentes AV OS",
    autorefractorOD: "Autorefractometro OD",
    autorefractorOS: "Autorefractometro OS",
    phoropterOD: "Foroptero OD",
    phoropterOS: "Foroptero OS",
    phoropterADD: "Foroptero ADD",
    lensesOD: "Lentes entregados OD",
    lensesOS: "Lentes entregados OS",
    lensesADD: "Lentes entregados ADD",
    visualAcuityLensesOD: "Agudeza Visual con Lentes AV OD",
    visualAcuityLensesOS: "Agudeza Visual con Lentes AV OS",

    //22
    accidentReport: "Reporte de Accidentes",
    accidentWork: "Accidente en el trabajo",
    description: "Descripción y especificar donde / como",

    traumaDetails: "Detalles del trauma",
    referralSpecialist: "Referencia a Especialista",
    followUpVisit: "Cita de seguimiento",
  },
  "ar": {
    patients: "المرضى",
    PATIENTS: "المرضى",
    welcome: "مرحبا بعودتك",
    dob: "تاريخ الولادة",
    DOB: "تاريخ الولادة",
    sex: "جنس",
    gender: "جنس",
    GENDER: "جنس",
    patientSummary: "ملخص المريض",
    noContent: "لا يوجد محتوى حتى الآن",
    age: "عمر",
    edit: "تعديل",
    back: "رجع",
    save: "حفظ",
    confirm: "تؤكد",
    cancel: "إلغاء",
    yes: "نعم",
    no: "لا",
    firstName: "الاسم المعطى",
    surname: "الكنية",
    country: "بلد",
    hometown: "مسقط رأس",
    selectDob: "اختر تاريخ الميلاد",
    phone: "هاتف",
    patientSearch: "البحث عن اسم المريض",
    search: "بحث",
    minAge: "الحد الإدنى للعمر",
    maxAge: "العمر الأقصى",
    advancedFilters: "مرشحات متقدمة ▼",
    hideFilters: "إخفاء المرشحات",
    clearFilters: "إعادة تعيين الفلاتر",
    camp: "مخيم",
    vitals: "الأعضاء الحيوية",
    examination: "فحص",
    notes: "ملاحظات",
    complaint: "شكوى",
    treatment: "علاج او معاملة",
    diagnosis: "التشخيص",
    medicineDispensed: "الأدوية المستغلة",
    prescriptions: "وصفات",
    allergies: "الحساسية",
    medicalHistory: "تاريخ طبى",
    covidScreening: "COVID-19 فحص",
    enterTextHere: "أدخل النص هنا",
    visitDate: "موعد زيارة",
    visitHistory: "زيارة التاريخ",
    visitEvents: "زيارة الأحداث",
    visitType: "نوع الزيارة",
    trends: "اتجاهات",
    eventType: "نوع الحدث",
    datePrescribed: "التاريخ المحدد",
    provider: "طبيب",
    severity: "خطورة",
    onsetDate: "تاريخ البداية",
    departure: "مغادرة",
    to: "إلى",
    return: "إرجاع",
    fever: "حمى؟",
    dryCough: "سعال جاف؟",
    diffBreathing: "صعوبة في التنفس؟",
    soreThroat: "إلتهاب الحلق؟",
    chestPain: "ألم في الصدر؟",
    confusion: "اضطراب إدراكي حديث؟",
    bluish: "الشفاه الزرقاء أم الوجه؟",
    fatigue: "إعياء؟",
    aches: "اوجاع والآم؟",
    headache: "صداع الراس؟",
    diabetes: "داء السكري؟",
    cardioDisease: "أمراض القلب والأوعية الدموية؟",
    pulmonaryDisease: "المرض الرئوي؟",
    renalDisease: "امراض الكلى؟",
    malignancy: "خباثة؟",
    pregnant: "حامل أو أسبوعين بعد الولادة؟",
    immunocompromised: "المنقوصي المناعة؟",
    exposureKnown: "الاتصال الأخير مع الأفراد المعروفين بفيروس التاجية؟",
    exposureSuspected: "الاتصال الأخير مع الأفراد الذين يشتبه أنهم فيروس التاجي؟",
    travelIran: "السفر الأخير إلى إيران؟",
    travel: "السفر الأخير إلى البلدان عالية المخاطر؟",
    testIsolate: "اختبار وعزل المريض",
    noAction: "لا رد فعل"
  }
};